plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
}

configurations {
	shadowDeps
	implementation.extendsFrom(shadowDeps)
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"servermagic" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// Web server
	shadowDeps 'io.javalin:javalin:5.6.3'
	shadowDeps 'com.fasterxml.jackson.core:jackson-databind:2.15.2'

	// JWT
	shadowDeps 'io.jsonwebtoken:jjwt-api:0.12.3'
	shadowDeps 'io.jsonwebtoken:jjwt-impl:0.12.3'
	shadowDeps 'io.jsonwebtoken:jjwt-jackson:0.12.3'

	// Database
	shadowDeps 'org.xerial:sqlite-jdbc:3.51.1.0'
	shadowDeps 'org.sql2o:sql2o:1.9.1'

	// SLF4J (provided by Minecraft at runtime)
	compileOnly 'org.slf4j:slf4j-api:2.0.9'

	// reflections (for auto-discovery of migrations/spells)
	shadowDeps 'org.reflections:reflections:0.10.2'
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}

	from {
		configurations.shadowDeps.collect { it.isDirectory() ? it : zipTree(it) }
	}
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	exclude 'META-INF/*.RSA', 'META-INF/*.SF', 'META-INF/*.DSA'
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}
