/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    InfoPage: typeof import('./src/components/info/InfoPage.vue')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    Message: typeof import('primevue/message')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    SecretsPage: typeof import('./src/components/secrets/SecretsPage.vue')['default']
    SideNavigation: typeof import('./src/components/SideNavigation.vue')['default']
    SkillDetailDialog: typeof import('./src/components/skilltree/SkillDetailDialog.vue')['default']
    SkillTree: typeof import('./src/components/skilltree/SkillTree.vue')['default']
    SkillTreePage: typeof import('./src/components/skilltree/SkillTreePage.vue')['default']
    SpellbookConfig: typeof import('./src/components/spellbook/SpellbookConfig.vue')['default']
    SpellCard: typeof import('./src/components/spellbook/SpellCard.vue')['default']
    SpellDetailsDialog: typeof import('./src/components/spellbook/SpellDetailsDialog.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    VanityPage: typeof import('./src/components/vanity/VanityPage.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
